-- 3)
SELECT * 
FROM employes;

-- 4)
SELECT EMPNO, EMPNOM, EMPSEXE 
FROM employes;

-- 5)
SELECT EMPNO, EMPNOM, EMPSALAIRE 
FROM employes 
WHERE EMPSEXE = 'F';

-- 6)
SELECT EMPNOM, EMPSALAIRE, SRVNO 
FROM employes 
WHERE SRVNO IN (1, 3, 6);

-- 7)
SELECT EMPNO, EMPNOM 
FROM employes 
WHERE EMPPRIME BETWEEN 500 AND 1000;

-- 8)
SELECT EMPNO, EMPNOM, SRVNO 
FROM employes 
WHERE EMPNOM LIKE 'D%';

-- 9)
SELECT EMPNO, EMPNOM, EMPPREN 
FROM employes 
WHERE EMPSEXE = 'M' 
ORDER BY EMPNOM ASC;

-- 10)
SELECT EMPNO, EMPNOM, EMPPREN, SRVNOM 
FROM employes, services 
WHERE employes.SRVNO = services.SRVNO AND EMPSALAIRE > 1000;

-- ext 1) chef de service
ALTER TABLE employes ADD CHEFSRV boolean;
INSERT INTO employes (EMPNO, EMPNOM, EMPPREN, EMPSEXE, SRVNO, CHEFSRV) VALUES
(21, 'Granchef', 'Yaka', 'M', 1, TRUE),
(22, 'Félécours', 'Yves', 'M', 2, TRUE),
(23, 'Maouane', 'Assiba', 'F', 3, TRUE),
(24, 'Teuse', 'Isabelle', 'F', 4, TRUE),
(25, 'Laplomb', 'Jérémy', 'M', 5, TRUE),
(26, 'Palherbe', 'Gaston', 'M', 6, TRUE);

-- ext 2) liste des employés avec qui il a affaire
SELECT * 
FROM employes 
ORDER BY SRVNO ASC, CHEFSRV DESC;

-- 11)
SELECT SRVNO, AVG(EMPSALAIRE) AS MOYSALAIRE
FROM employes 
GROUP BY SRVNO;

-- 12)
SELECT EMPNOM, EMPPREN, EMPSALAIRE 
FROM employes 
WHERE EMPSALAIRE > (SELECT EMPSALAIRE 
                    FROM employes 
                    WHERE EMPNO = 11);

-- 13)
SELECT SRVNO, AVG(EMPSALAIRE) AS MOYSALAIRE
FROM employes
GROUP BY SRVNO
HAVING AVG(EMPSALAIRE) < (SELECT AVG(EMPSALAIRE) 
                          FROM employes);

-- 14)
SELECT projets.SRVNO, PROJLIB, SRVNOM 
FROM services, projets 
WHERE services.SRVNO = projets.SRVNO 
ORDER BY SRVNO ASC;

-- 15)
SELECT PROJLIB 
FROM employes, projets, intervenir 
WHERE intervenir.PROJNO = projets.PROJNO AND intervenir.EMPNO = employes.EMPNO AND EMPNOM = 'DESTIN'
ORDER BY PROJLIB ASC;

-- 16)
SELECT SRVNO, EMPNOM, EMPNO 
FROM employes 
WHERE EMPSEXE = 'M' AND EMPPRIME > 800 
ORDER BY SRVNO, EMPNOM;

-- 17)
SELECT SRVNO, EMPNOM, EMPPREN, EMPSALAIRE + EMPPRIME AS SALAIREPRIME
FROM employes 
WHERE SRVNO IN (1, 2, 4)
ORDER BY SRVNO ASC, TOTAL desc;

-- 18)
SELECT SUM(EMPSALAIRE) AS SOMMESALAIRE, MIN(EMPSALAIRE) AS MINSALAIRE, MAX(EMPSALAIRE) AS MAXSALAIRE
FROM employes;

-- 19)
SELECT COUNT(SRVNO) 
FROM employes;

-- 20)
SELECT services.SRVNO, SRVNOM, AVG(EMPPRIME) AS MOYPRIME
FROM employes, services 
WHERE employes.SRVNO = services.SRVNO 
GROUP BY SRVNO;

-- 21)
SELECT PROJLIB 
FROM projets, intervenir 
WHERE projets.PROJNO = intervenir.PROJNO 
GROUP BY projets.PROJNO 
HAVING SUM(NBHEURES) > 120;

-- 22)
SELECT intervenir.EMPNO, EMPNOM, EMPPREN, SUM(NBHEURES) AS SOMMEHEURES
FROM employes, intervenir 
WHERE employes.EMPNO = intervenir.EMPNO 
GROUP BY EMPNOM 
HAVING SUM(NBHEURES) > 20 
ORDER BY SUM(NBHEURES) DESC;