-- 3)
SELECT * FROM employes;

-- 4)
SELECT EMPNO, EMPNOM, EMPSEXE FROM employes;

-- 5)
SELECT EMPNO, EMPNOM, EMPSALAIRE FROM employes WHERE EMPSEXE = 'F';

-- 6)
SELECT EMPNOM, EMPSALAIRE, SRVNO FROM employes WHERE SRVNO = 1 OR SRVNO = 3 OR SRVNO = 6;

-- 7)
SELECT EMPNO, EMPNOM FROM employes WHERE EMPPRIME BETWEEN 500 AND 1000;

-- 8)
SELECT EMPNO, EMPNOM, SRVNO FROM employes WHERE EMPNOM LIKE 'D%';

-- 9)
SELECT EMPNO, EMPNOM, EMPPREN FROM employes WHERE EMPSEXE = 'M' ORDER BY EMPNOM ASC;

-- 10)
SELECT EMPNO, EMPNOM, EMPPREN, SRVNOM FROM employes, services WHERE employes.SRVNO = services.SRVNO AND EMPSALAIRE > 1000;